version: "3.8"

services:
  rust_server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - mysql_primary
      - mysql_backup
    volumes:
      - ./secrets/id.json:/app/secrets/id.json
    environment:
      - WALLET_PATH=/app/secrets/id.json
      - DATABASE_URL=mysql://root:password@mysql_primary:3306/primary_database
      - DATABASE_RR_URL=mysql://root:password@mysql_backup:3306/backup_database
      - RPC_URL=https://mainnet.helius-rpc.com/?api-key=a4184ebc-516f-4432-a449-78b8dd47e6bf
      - RPC_WS_URL=wss://mainnet.helius-rpc.com/?api-key=a4184ebc-516f-4432-a449-78b8dd47e6bf
      - PASSWORD="password"
    networks:
      - mynetwork

  mysql_primary:
    image: mysql:8.0
    ports:
      - "3307:3306" # Expose on a different host port to avoid conflicts
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: primary_database
      MYSQL_USER: user
      MYSQL_PASSWORD: user_password
    networks:
      - mynetwork

  mysql_backup:
    image: mysql:8.0
    ports:
      - "3308:3306" # Expose on a different host port to avoid conflicts
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: backup_database
      MYSQL_USER: user
      MYSQL_PASSWORD: user_password
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
